# Domínios de e-mail descartáveis/temporários bloqueados
# Lista curada dos serviços mais usados para e-mails temporários

DISPOSABLE_DOMAINS: frozenset[str] = frozenset({
    # 10 Minute Mail e variantes
    "10minutemail.com", "10minutemail.net", "10minutemail.org",
    "10minutemail.de", "10minutemail.co.uk", "10minutemail.us",
    "10minutemail.be", "10minutemail.cf", "10minutemail.ga",
    "10minutemail.info", "10minemail.com", "10mail.org",
    "tenminutemail.com", "tenminutemail.net", "10minutemail.ru",
    # Guerrilla Mail
    "guerrillamail.com", "guerrillamail.net", "guerrillamail.org",
    "guerrillamail.de", "guerrillamail.biz", "guerrillamail.info",
    "guerrillamailblock.com", "grr.la", "spam4.me",
    # Mailinator e variantes
    "mailinator.com", "mailinator2.com", "mailinator.net",
    "mailinater.com", "suremail.info", "spamherelots.com",
    "spamhereplease.com", "sendspamhere.com", "girlsundertheinfluence.com",
    "iheartspam.org", "junkemailgenerator.com", "yopmail.com",
    # Yopmail e variantes
    "yopmail.fr", "yopmail.net", "cool.fr.nf", "jetable.fr.nf",
    "nospam.ze.tc", "nomail.xl.cx", "mega.zik.dj", "speed.1s.fr",
    "courriel.fr.nf", "moncourrier.fr.nf", "monemail.fr.nf",
    "monmail.fr.nf", "yopmail.pp.ua",
    # Temp Mail
    "temp-mail.org", "tempmail.com", "tempmail.net", "tempmail.io",
    "temp-mail.ru", "tempmail.de", "tempr.email", "dispostable.com",
    "tempinbox.com", "tempinbox.co.uk", "throwam.com",
    # Throwaway e descartáveis populares
    "throwaway.email", "throwam.com", "throwam.net", "throwam.org",
    "mailnull.com", "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
    "spamgourmet.com", "mailnull.com", "trashmail.com", "trashmail.net",
    "trashmail.org", "trashmail.at", "trashmail.de", "trashmail.io",
    "trashmail.me", "trashmail.xyz", "trashemail.de",
    # Fake email services
    "fakeinbox.com", "fakeinbox.net", "fakeinbox.org",
    "fakemailgenerator.com", "fakemail.fr", "fakemail.net",
    "maildrop.cc", "mailnesia.com", "mailnull.com",
    # Sharklasers / Guerrilla sub-services
    "sharklasers.com", "guerrillamailblock.com", "jetable.pp.ua",
    "spam.la", "bund.us", "jetable.net", "jetable.org",
    # Discard.email
    "discard.email", "discardmail.com", "discardmail.de",
    "spamspot.com", "spamthisplease.com", "spamfree24.org",
    "spamfree.eu", "spam.su", "spambob.com", "spambob.net",
    "spambob.org",
    # Mohmal
    "mohmal.com", "mohmal.im", "mohmal.tech",
    # Mailtemp
    "mailtemp.info", "mailtemp.net", "mailtemp.org",
    "emailtemp.org", "tempail.com", "emkei.cz",
    # Outros populares
    "getnada.com", "nada.email", "filzmail.com", "filzmail.de",
    "cust.in", "spamavert.com", "owlpic.com", "spamex.com",
    "spamfree.eu", "spamgap.com", "spamgob.com", "spamhereplease.com",
    "spamhole.com", "spamify.com", "spamthisplease.com",
    "deadaddress.com", "deadfake.com", "dispostable.com",
    "dontreg.com", "dontsendmespam.de", "dump-email.info",
    "dumpandfuck.com", "dumpyemail.com", "e4ward.com",
    "einmalmail.de", "email60.com", "emailias.com",
    "emailinfive.com", "emailisvalid.com", "emailmiser.com",
    "emailsensei.com", "emailtemporanea.com", "emailtemporanea.net",
    "emailtemporar.ro", "emailtemporario.com.br",
    "emailthe.net", "emailtmp.com", "emailto.de",
    "emailwarden.com", "emailx.at.hm", "emailxfer.com",
    "emz.net", "enterto.com", "ephemail.net", "etranquil.com",
    "etranquil.net", "etranquil.org", "everytick.com",
    "explodemail.com", "express.net.ua", "extremail.ru",
    "eyepaste.com", "fakemailz.com", "fammix.com",
    "fansworldwide.de", "fantasticmail.com", "fast-email.com",
    "fastem.com", "fastemail.us", "fastemailer.com",
    "fastest.cc", "fastimap.com", "fastmailbox.net",
    "fightallspam.com", "fleckens.hu", "flopmail.com",
    "flyspam.com", "forgetmail.com", "fr33mail.info",
    "frapmail.com", "fuckingduh.com", "fudgerub.com",
    "fun2.biz", "galvanis.ru", "gawab.com",
    "get-mail.pl", "get1mail.com", "getair.eu",
    "getcoolmail.info", "getmails.eu", "getonemail.com",
    "getonemail.net", "ghosttexter.de", "girlsundertheinfluence.com",
    "givmail.com", "glubex.com", "gmailnew.com",
    "gothere.biz", "gowikibooks.com", "gowikicampus.com",
    "gowikicars.com", "gowikifilms.com", "gowikigames.com",
    "gowikimusic.com", "gowikinetwork.com", "gowikitravel.com",
    "gowikitv.com", "grandmamail.com", "grandmasmail.com",
    "great-host.in", "greensloth.com", "grungecafe.com",
    "gsrv.co.uk", "gustr.com", "h.mintemail.com",
    "h8s.org", "haltospam.com", "hatespam.org",
    "herp.in", "hidemail.de", "hidzz.com",
    "hmamail.com", "hopemail.biz", "hostcalls.com",
    "hot-mail.cf", "hot-mail.ga", "hot-mail.gq",
    "hot-mail.ml", "hot-mail.tk", "hotpop.com",
    "hulapla.de", "hush.ai", "hushmail.com",
    "ieatspam.eu", "ieatspam.info", "ieh-mail.de",
    "ignoremail.com", "ihateyoualot.info", "iheartspam.org",
    "imails.info", "inbax.tk", "inbox.si",
    "inboxalias.com", "inboxclean.com", "inboxclean.org",
    "inboxdesign.me", "inboxed.pw", "inboxstore.me",
    "incognitomail.com", "incognitomail.net", "incognitomail.org",
    "inoutmail.de", "inoutmail.eu", "inoutmail.info",
    "inoutmail.net", "insorg-mail.info", "instant-mail.de",
    "instantemailaddress.com", "instantmail.fr",
    "internet-e-mail.de", "internet-mail.de", "internetemails.net",
    "internetmailing.net", "inwind.it", "ioio.eu",
    "ip6.li", "ipoo.org", "irish2me.com",
    "iroid.com", "isignup.org", "iwi.net",
    "jetable.com", "jetable.fr.nf", "jnxjn.com",
    "jourrapide.com", "junk.to", "junkmail.com",
    "junkmail.ga", "junkmail.gq", "kasmail.com",
    "kaspop.com", "keepmymail.com", "killmail.com",
    "killmail.net", "kir.ch.tc", "klassmaster.com",
    "klassmaster.net", "klassmaster.org", "klzlk.com",
    "koszmail.pl", "kurzepost.de", "letthemeatspam.com",
    "liveradio.tk", "llogin.ml", "lol.ovpn.to",
    "lolfreak.net", "lookugly.com", "lortemail.dk",
    "losemymail.com", "lovemeleaveme.com", "luggage.email",
    "lukemail.com", "lurothers.xyz", "mailbiz.biz",
    "mailblocks.com", "mailbucket.org", "mailchop.com",
    "maildrop.cc", "maileimer.de", "mailexpire.com",
    "mailf5.com", "mailfall.com", "mailfree.ga",
    "mailfreeonline.com", "mailfs.com", "mailguard.me",
    "mailhazard.com", "mailhazard.us", "mailimate.com",
    "mailin8r.com", "mailinater.com", "mailismagic.com",
    "mailme.ir", "mailme.lv", "mailme24.com",
    "mailmetrash.com", "mailmoat.com", "mailnew.com",
    "mailnull.com", "mailpick.biz", "mailproxsy.com",
    "mailquack.com", "mailrock.biz", "mailscrap.com",
    "mailseal.de", "mailshell.com", "mailsiphon.com",
    "mailslapping.com", "mailslite.com", "mailsponge.com",
    "mailtemp.de", "mailtome.de", "mailtothis.com",
    "mailtrash.net", "mailtv.net", "mailtv.tv",
    "mailzilla.com", "mailzilla.org", "makemetheking.com",
    "manybrain.com", "mbx.cc", "mega.zik.dj",
    "meinspamschutz.de", "meltmail.com", "messagebeamer.de",
    "mezimages.net", "mierdamail.com", "mintemail.com",
    "misterpinball.de", "mjukglass.nu", "moakt.cc",
    "moakt.co", "moakt.com", "moakt.ws",
    "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf",
    "mox.pp.ua", "mt2009.com", "mt2014.com",
    "mt2015.com", "muchomail.com", "mucincanon.com",
    "mundomail.net", "mx0.wwwnew.eu", "my10minutemail.com",
    "myalias.pw", "mycard.net.ua", "mycleaninbox.net",
    "mydissposableemail.com", "myemailboxy.com", "myfastmail.com",
    "mymailoasis.com", "mynetstore.de", "mypacks.net",
    "mypartyclip.de", "myphantomemail.com", "mysamp.de",
    "myspaceinc.com", "myspaceinc.net", "myspaceinc.org",
    "myspacepimped.com", "mytemp.email", "mytempemail.com",
    "mythrowaway.email", "mytrashmail.com",
    # Brasileiros e latinos
    "emailtemporario.com.br", "tempmail.com.br",
    "correotemporal.org", "desechable.com",
    # Novos serviços comuns
    "guerrillamail.info", "nwldx.com", "onetimemail.net",
    "owlymail.com", "pookmail.com", "privy-mail.com",
    "privy-mail.de", "proxymail.eu", "punkass.com",
    "putthisinyourspamdatabase.com", "qq.com", "rainmail.biz",
    "randomail.net", "rcpt.at", "reallymymail.com",
    "recode.me", "recursor.net", "regbypass.com",
    "regbypass.comsafe-mail.net", "rejectmail.com",
    "rMailt.com", "rootfest.net", "rottenmail.com",
    "rvb.ro", "s0ny.net", "safe-mail.net",
    "safetymail.info", "safetypost.de", "sandelf.de",
    "saynotospams.com", "selfdestructingmail.com",
    "sendspamhere.com", "sharedmailbox.org", "sharklasers.com",
    "shieldedmail.com", "shitmail.de", "shitmail.me",
    "shitmail.org", "shitware.nl", "shmeriously.com",
    "shortmail.net", "sibmail.com", "skeefmail.com",
    "slapsfromlastnight.com", "slaskpost.se", "slave-auctions.net",
    "slippery.email", "slopsbox.com", "slowslow.de",
    "smellfear.com", "snakemail.com", "sneakemail.com",
    "sneakmail.de", "snkmail.com", "sofimail.com",
    "sofort-mail.de", "sogetthis.com", "soisz.com",
    "sol.dk", "spam.la", "spam.su",
    "spam4.me", "spamavert.com", "spambob.com",
    "spambob.net", "spambob.org", "spambog.com",
    "spambog.de", "spambog.ru", "spambox.info",
    "spambox.irishspringrealty.com", "spambox.us", "spamcannon.com",
    "spamcannon.net", "spamcero.com", "spamcon.org",
    "spamcorptastic.com", "spamcowboy.com", "spamcowboy.net",
    "spamcowboy.org", "spamday.com", "spamex.com",
    "spamfree.eu", "spamfree24.org", "spamgap.com",
    "spamgob.com", "spamgourmet.com", "spamgourmet.net",
    "spamgourmet.org", "spamherelots.com", "spamhereplease.com",
    "spamhole.com", "spamify.com", "spaminator.de",
    "spamkill.info", "spaml.com", "spaml.de",
    "spammotel.com", "spamobox.com", "spamoff.de",
    "spamsalad.in", "spamslicer.com", "spamspot.com",
    "spamstack.net", "spamthis.co.uk", "spamthisplease.com",
    "spamtroll.net", "spamwc.de", "spamwc.net",
    "spamwc.org", "speed.1s.fr", "spoofmail.de",
    "squizzy.de", "squizzy.eu", "squizzy.net",
    "startkeys.com", "stinkefinger.net", "stuffmail.de",
    "super-auswahl.de", "supergreatmail.com", "supermailer.jp",
    "superrito.com", "superstachel.de", "suremail.info",
    "svkmail.com", "sweetxxx.de", "tafmail.com",
    "tagyourself.com", "teewars.org", "teleworm.com",
    "teleworm.us", "temp-mail.com", "temp-mail.de",
    "temp-mail.net", "temp.emeraldwebmail.com", "tempail.com",
    "tempalias.com", "tempemails.net", "tempinbox.co.uk",
    "tempinbox.com", "tempmail.eu", "tempmail.it",
    "tempmail2.com", "tempomail.fr", "temporaryemail.net",
    "temporaryemail.us", "temporaryforwarding.com",
    "temporaryinbox.com", "temporamail.com", "temporaryemail.com",
    "thankyou2010.com", "thecloudindex.com",
    "thisisnotmyrealemail.com", "thismail.net", "thismail.ru",
    "throwam.com", "throwaway.email", "throwam.net",
    "tilien.com", "tittbit.in", "tizi.com",
    "tmail.com", "tmail.io", "tmail1.com",
    "toiea.com", "tokenmail.de", "toomail.biz",
    "topranklist.de", "tradermail.info", "trash-mail.at",
    "trash-mail.com", "trash-mail.de", "trash-mail.ga",
    "trash-mail.io", "trash-mail.ml", "trash-mail.net",
    "trash-mail.tk", "trash2009.com", "trash2010.com",
    "trash2011.com", "trashdevil.com", "trashdevil.de",
    "trashemail.de", "trashmail.at", "trashmail.com",
    "trashmail.de", "trashmail.io", "trashmail.me",
    "trashmail.net", "trashmail.org", "trashmail.xyz",
    "trashmailer.com", "trashspam.com", "trillianpro.com",
    "trushmail.com", "ttirv.com", "ttirv.net",
    "ttirv.org", "tucows.com", "turual.com",
    "twinmail.de", "twoweirdtricks.com", "tyldd.com",
    "uggsrock.com", "umail.net", "uroid.com",
    "us.af", "uwork4.us", "venompen.com",
    "veryrealemail.com", "vidchart.com", "viditag.com",
    "viewcastmedia.com", "viewcastmedia.net", "viewcastmedia.org",
    "viralplays.com", "vomoto.com", "vpn.st",
    "vsimcard.com", "vubby.com", "w3internet.co.uk",
    "walala.org", "walkmail.net", "walkmail.ru",
    "webemail.me", "webm4il.info", "wegwerfadresse.de",
    "wegwerfemail.com", "wegwerfemail.de", "wegwerfmail.de",
    "wegwerfmail.info", "wegwerfmail.net", "wegwerfmail.org",
    "wh4f.org", "whatiaas.com", "whatpaas.com",
    "whatsaas.com", "whopy.com", "wilemail.com",
    "willhackforfood.biz", "willselfdestruct.com", "winemaven.info",
    "wronghead.com", "wuzupmail.net", "www.e4ward.com",
    "www.gishpuppy.com", "www.mailbolt.com", "wwwnew.eu",
    "xagloo.co", "xagloo.com", "xemaps.com",
    "xents.com", "xmaily.com", "xoxy.net",
    "xyzmail.tk", "yapped.net", "yeah.net",
    "yep.it", "yogamaven.com", "yopmail.com",
    "yopmail.fr", "yopmail.net", "youmailr.com",
    "yourlms.biz", "ypmail.webarnak.fr.eu.org",
    "yuurok.com", "z1p.biz", "za.com",
    "zaktouni.fr", "zap-email.com", "zappybits.com",
    "zed.infona.pl", "zehnminutenmail.de", "zetmail.com",
    "zippymail.info", "zoaxe.com", "zoemail.com",
    "zoemail.net", "zoemail.org", "zomg.info",
    "zxcv.com", "zxcvbnm.com", "zzz.com",
})


def is_disposable_email(email: str) -> bool:
    """Retorna True se o domínio do e-mail for descartável/temporário."""
    email = email.strip().lower()
    if "@" not in email:
        return False
    domain = email.split("@", 1)[1]
    return domain in DISPOSABLE_DOMAINS
